package com.kerneldc.hangariot.mqtt.topic;

public enum TopicEnum {
	COMMAND_POWER_TOPIC,	
	COMMAND_TELEMETRY_PERIOD_TOPIC,
	COMMAND_TIMEZONE_TOPIC,
	STATE_RESULT_TOPIC,
	STATE_POWER_TOPIC,
	TELEMETRY_SENSOR_TOPIC;
	
}
